//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookTakeout.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BookTakeout.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book saved to file: &quot;{0}&quot;..
        /// </summary>
        public static string BookSavedToFileX {
            get {
                return ResourceManager.GetString("BookSavedToFileX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chapters {0} of {1}.
        /// </summary>
        public static string ChaptersXOfY {
            get {
                return ResourceManager.GetString("ChaptersXOfY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done..
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading book content..
        /// </summary>
        public static string DownloadingBookContent {
            get {
                return ResourceManager.GetString("DownloadingBookContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading content for book {0}..
        /// </summary>
        public static string DownloadingContentForBookX {
            get {
                return ResourceManager.GetString("DownloadingContentForBookX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading information about all books..
        /// </summary>
        public static string DownloadingInformationAboutAllBooks {
            get {
                return ResourceManager.GetString("DownloadingInformationAboutAllBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading information about the book..
        /// </summary>
        public static string DownloadingInformationAboutBook {
            get {
                return ResourceManager.GetString("DownloadingInformationAboutBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid URL(s)..
        /// </summary>
        public static string EnterValidUrls {
            get {
                return ResourceManager.GetString("EnterValidUrls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: {0}..
        /// </summary>
        public static string ErrorX {
            get {
                return ResourceManager.GetString("ErrorX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to download book {0}..
        /// </summary>
        public static string FailedToDownloadBookX {
            get {
                return ResourceManager.GetString("FailedToDownloadBookX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid book URL skipped: {0}..
        /// </summary>
        public static string InvalidBookUrlSkippedX {
            get {
                return ResourceManager.GetString("InvalidBookUrlSkippedX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading chapters ({0}/{1}).
        /// </summary>
        public static string LoadingChaptersXOfY {
            get {
                return ResourceManager.GetString("LoadingChaptersXOfY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No valid book URLs provided..
        /// </summary>
        public static string NoValidUrlsProvided {
            get {
                return ResourceManager.GetString("NoValidUrlsProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &quot;{0}&quot; is required in non-interactive mode..
        /// </summary>
        public static string ParameterXIsRequiredInNonInteractiveMode {
            get {
                return ResourceManager.GetString("ParameterXIsRequiredInNonInteractiveMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press any key to exit....
        /// </summary>
        public static string PressAnyKeyToExit {
            get {
                return ResourceManager.GetString("PressAnyKeyToExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully authenticated as: {0}..
        /// </summary>
        public static string SuccessfullyAuthenticatedAsX {
            get {
                return ResourceManager.GetString("SuccessfullyAuthenticatedAsX", resourceCulture);
            }
        }
    }
}
