name: Build & Release Installer

on:
    push:
        tags:
            - 'v*.*.*'

permissions:
    contents: write

jobs:
    build:
        runs-on: windows-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Setup .NET
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: '10.0.x'

            - name: Restore Dependencies
              run: dotnet restore

            - name: Build Application
              run: dotnet build --configuration Release --no-restore

            - name: Publish Application
              run: dotnet publish --self-contained -r win-x64

            - name: Compile Inno Setup Script
              uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
              with:
                  path: ./setup/BookTakeout.Console.iss

            - name: Create GitHub Release
              uses: softprops/action-gh-release@v2
              with:
                  files: ./artifacts/setup/BookTakeout_v*.exe
                  generate_release_notes: true